---
output:
  pdf_document:
    keep_tex: true
    fig_caption: yes
    latex_engine: pdflatex
geometry: margin=1in

bibliography: ../library.bib
csl: ../apa.csl

title: "Le Modèle de Markowitz"
author: Patrick Hénaff
date: "Version: `r format(Sys.Date(), '%d %b %Y')`"
email: "pa.henaff@gmail.com"

fontfamily: mathpazo
fontsize: 11pt
header-includes:
   - \linespread{1.05}
   - \usepackage[utf8]{inputenc}
   - \usepackage{amsthm}
   - \usepackage{xfrac}
---

```{r setup, include=FALSE, cache=F, message=F, warning=F, results="hide"}
knitr::opts_chunk$set(cache=TRUE)
knitr::opts_chunk$set(fig.path='figs/')
knitr::opts_chunk$set(cache.path='_cache/')
knitr::opts_chunk$set(warning=F, message=F)
```

\newcommand{\ones}{\mathbf{1}}
\newcommand{\onesT}{\mathbf{1}^T}

\newtheorem{thm}{Theorem}

In this short note, we summarize the mathematical elements of the classical portfolio theory of Markowitz. Today, the benefits of diversification seem unquestionable. But it has not always been that way: in 1934, the famous economist and investor J. M. Keynes wrote this to the chairman of an insurance company:

> "As time goes on I get more and more convinced that the right method in investment
> is to put fairly large sums into enterprises which one thinks one
> knows something
> about and in the management of which one thoroughly believes."

We too will keep this advice in mind as we review Markowitz's contribution.

# Arithmetic vs. Geometric mean

Let $r_A$ and $r_G$ be, respectively, the arithmetic and geometric means of a series of returns:

\begin{align*}
r_A &= \frac{1}{n} \sum_{k=1}^n r_k \\
r_G &= \prod_{k=1}^n (1+r_k)^{1/n} - 1
\end{align*}

and let $V$ be the variance of $r_k$. We show that the geometric mean, which correctly represents the increase in wealth from an investment, is lower than the arithmetic mean.

The MacLaurin series for $(1+x)^{1/n}$ is:

$$
(1+x)^\frac{1}{n} = 1 + \frac{1}{n} x + \frac{1-n}{n^2} \frac{x^2}{2} + o(x^2)
$$


$$
r_G \approx \prod_{k=1}^n \left(1 + \frac{1}{n} r_k + \frac{1-n}{n^2} \frac{r_k^2}{2} \right) - 1
$$

Developping the product and keeping terms of order 2,

$$
r_G \approx \frac{1}{n} \sum_k r_k + \frac{1}{n^2} \sum_{k \neq l} r_k r_l + \frac{1-n}{2n^2} r^2_k
$$

\begin{align}
r_G & \approx r_A - \frac{1}{2} \left[ \frac{1}{n} \sum_k r^2_k - \frac{1}{n^2} \left( \sum_k r^2_k + 2 \sum_{k \neq l} r_k r_l \right) \right] \\
& \approx r_A - \frac{1}{2} \left[ \frac{1}{n} \sum_k r^2_k - \left(  \frac{1}{n} \sum_k r_k  \right)^2 \right] \\
& \approx r_A - \frac{1}{2} V, \ \ V >= 0
\end{align}



# Quadratic Programming

## QP with equality constraints

$$
\begin{aligned}
    \mbox{min} \ \ & \frac{1}{2} w^T \Sigma w  \\
    \mbox{s.t.} & \\
    & A^T w  = b
  \end{aligned}
$$

Lagrangian:

$$
L(w, \lambda) = \frac{1}{2} w^T \Sigma w - \lambda^T \left(A^Tw -b \right)
$$

First order conditions:

$$
\left\{
                \begin{aligned}
                \Sigma w - A \lambda &= 0 \\
                A^Tw & = b
                \end{aligned}
              \right.
$$

or,

$$
\begin{bmatrix} \Sigma & -A \\ A^T & 0 \end{bmatrix}  \left[ \begin{array}{c} w \\ \lambda \end{array} \right] = \left[ \begin{array}{c} 0 \\ b \end{array} \right]
$$


## Special case of Minimum Variance problem

$$
A = \begin{bmatrix} 1  \\ \vdots  \\ 1\end{bmatrix} \ \ \ b = 1
$$

Solution:

$$
w = \lambda \Sigma^{-1} A
$$

Normalize so that weights sum to 1:

$$
w = \frac{\Sigma^{-1} \mathbf{1}}{\mathbf{1}^T\Sigma^{-1}\mathbf{1}}
$$

# Mean-Variance model [@Markowitz1952]

$$
\begin{aligned}
    \mbox{min} \ \ & \frac{1}{2} w^T \Sigma w  \\
    \mbox{s.t.} & \\
    \mathbf{1}^Tw & = 1 \\
        R^Tw & = R_P
  \end{aligned}
$$

Lagrangian:

$$
L(w, \lambda_1, \lambda_2) = \frac{1}{2} w^T \Sigma w - \lambda_1(\mathbf{1}^Tw-1) -\lambda_2(R^Tw - R_P)
$$

Solution of first order conditions:


\begin{equation}
\left\{
                \begin{aligned}
                \Sigma w - \lambda_1 \mathbf{1} -\lambda_2 R  &= 0 \label{eq:eq-1} \\
                \mathbf{1}^T w &= 1 \\
                R^Tw & = R_P
                \end{aligned}
              \right.
\end{equation}

Determination of $\lambda_1$ and $\lambda_2$:

$$
w = \Sigma^{-1} (\lambda_1 \mathbf{1} + \lambda_2 R)
$$

Define:


\begin{align*}
                a & = \onesT \Sigma^{-1} \ones \\
                b & = \onesT \Sigma^{-1} R \\
                c & = R^T \Sigma^{-1} R
                \end{align*}


Substitute in (\ref{eq:eq-1}):

\begin{equation*}
\left\{
                \begin{aligned}
                \lambda_1 a + \lambda_2 b & = 1 \\
                \lambda_1 b + \lambda_2 c & = R_P
                \end{aligned}
              \right.
\end{equation*}

Solution:

\begin{align*}
                \lambda_1 & = \frac{c - b R_P}{\Delta} \\
                \lambda_2 & = \frac{a R_P - b}{\Delta} \\
                \Delta & = ac - b^2
                \end{align*}


Note that:

\begin{align*}
\sigma^2_P & = w^{*T} \Sigma w^* \\
& = w^{*T} \Sigma \left( \lambda_1 \Sigma^{-1} \ones + \lambda_2 \Sigma^{-1} R \right) \\
& = \lambda_1 + \lambda_2 R_P
\end{align*}

Two remarkable solutions:

+ Minimum variance portfolio

\begin{align*}
\frac{\partial \sigma^2_P}{\partial R_P} & = 0 \implies \\
\frac{2 a R_P - 2b}{\Delta} & = 0 \implies \\
R_P & = \frac{b}{a} \\
\sigma^2_P &= \frac{1}{a} \\
\lambda_1 &=  \frac{1}{a} \\
\lambda_2 &=  0
\end{align*}

The weights of the minimum variance portfolio:

\begin{align*}
w_g & = \lambda_1 \Sigma^{-1} \ones \\
& = \frac{\Sigma^{-1} \ones}{\onesT \Sigma^{-1} \ones}
\end{align*}


+ $\lambda_1 = 0$

This second solution gives $\lambda_2 = \frac{1}{b}$ and the optimal weights:

\begin{align*}
w_d & = \lambda_2 \Sigma^{-1} R \\
& = \frac{\Sigma^{-1} R}{\onesT \Sigma^{-1} R}
\end{align*}


\begin{thm}\label{thm:mv-1}
Any MV optimal portfolio $w^*_P$ with expected excess return $R_P$ can be decomposed into two MV portfolios.

$$
w^*_P = A w_g + (1-A) w_d
$$
\end{thm}

\begin{proof}
Since $w_P$ is MV optimal,
\begin{align*}
w_P &= \lambda_1 \Sigma^{-1} \ones + \lambda_2 \Sigma^{-1} R \\
&= \lambda_1 a w_g + \lambda_2 b w_d
\end{align*}

One can verify that
$$
\lambda_1 a  + \lambda_2 b = 1
$$
\end{proof}

## MV model with riskless asset

The tangency portfolio corresponds to the point on the efficient frontier where the
slope of the tangent $\frac{R_M - r_f}{\sigma_M}$ is maximized, where:

$$
\frac{R_M - r_f}{\sigma_M} = \frac{w^T (R - R_f)}{\sqrt{w^T \Sigma w}}
$$

Noting that the slope is unchanged when the weights $w$ are multiplied by a constant, the tangency portfolio is found by solving the following QP problem for an arbitrary $R^*>R_f$:

$$
\begin{aligned}
    \mbox{min} \ \ & \frac{1}{2} w^T \Sigma w  \\
    \mbox{s.t.} & \\
        \tilde{R}^Tw & = R^*
  \end{aligned}
$$

with $\tilde{R} = R-R_f$.

Lagrangian:

$$
L(w, \lambda) = \frac{1}{2} w^T \Sigma w - \lambda \left(\tilde{R}^Tw - R^* \right)
$$

Which yields:

\begin{equation}
w^* = \lambda^* \Sigma^{-1} \tilde{R}
\label{eq:w-star}
\end{equation}

Normalize so that the weights sum to 1:

\begin{equation}
w^* = \frac{\Sigma^{-1} \tilde{R}}{\onesT \Sigma^{-1} \tilde{R}}
\label{eq:sharpe}
\end{equation}

The corresponding expected excess return is given by:

$$
E(R^*_P) = \frac{\tilde{R}^T \Sigma^{-1} \tilde{R}}{\onesT \Sigma^{-1} \tilde{R}}
$$


## Maximum Sharpe ratio for two risky assets

Given two assets, A and M, the allocation that maximizes the Sharpe ratio is given by:

\begin{equation}
w_A = \frac{R_A \sigma^2_M - R_M \sigma_A \sigma_M \rho_{AM}}{R_A \sigma^2_M + R_M \sigma^2_A - (R_A+R_M) \sigma_A \sigma_M \rho_{AM}}
\label{eq:wA}
\end{equation}

\begin{proof}
Use equation (\ref{eq:sharpe}) with
\begin{equation}
\Sigma = \begin{bmatrix} \sigma^2_A & \rho \sigma_A \sigma_M \\ \rho \sigma_A \sigma_M & \sigma^2_M \end{bmatrix}
\label{eq:sigma}
\end{equation}

$$
\Sigma^{-1} = \frac{1}{(1-\rho^2) \sigma^2_A\sigma^2_M} \begin{bmatrix} \sigma^2_M & -\rho \sigma_A \sigma_M \\ -\rho \sigma_A \sigma_M & \sigma^2_A \end{bmatrix}
$$
\end{proof}

# Bibliography



